### ISSUE TITLE
No data locally in /home/pi/Documents/fbfs_log.csv

### ISSUE THREAD

**Issue by VeggieVampire** [microsoft/farmbeatsforstudents#5]
I am unable to see any data in /home/pi/Documents/fbfs_log.csv

but when I connect a computer I can see everything on the com port and in the excel spreadsheet. Just trying to read the data without the computer connected.  Any way to read the serial data stream locally on the pi?

**Comment by damyka** [comment]
Hi @VeggieVampire, this is by design. The file (/home/pi/Documents/fbfs_log.csv) is a log file only gets written to once an hour. 

If you want to change this the time interval is managed in [main.py, line 74](https://github.com/microsoft/farmbeatsforstudents/blob/3094997d1a5f065803c345fc13e3ae18d9d3138e/farmbeats-datastreamer/main.py#L74). 

Since the farmbeats python app is attached to the serial port (dev/ttyS0) you would need an application like [serial port monitor for Linux](https://ioninja.com/plugins/serial-monitor.html) to be able to see serial data and events from other applications.

I hope this helps!

**Comment by VeggieVampire** [comment]
Thanks for the reply but I've have this on for weeks and nothing ever writes in the directory. Is there anything I need to do to start it without connecting to the serial port?

**Comment by damyka** [comment]
OK, I understand. By default data logging must be initiated by the user. Using the [custom Excel workbook](https://aka.ms/FBFSWorkbook), there is a **Start logging data** button on the **Data Journal** worksheet in the workbook that will send a start logging command to the Pi. Once started, the logger will write data once per hour and will continue until a end logging command is sent to the Pi.

There is a set of commands to control the logger functionality that you can read about [here](https://github.com/microsoft/farmbeatsforstudents/tree/main/farmbeats-datastreamer#data-logger). These commands can also be sent to the Pi using a serial terminal.
