### ISSUE TITLE
Farmer kit problem

### ISSUE THREAD

**Issue by mdadamo89** [microsoft/farmbeatsforstudents#7]
I have several problems with the installation of sensors on the raspberry, as it brings me error. But even if it does not give me error in the process of data streamer when I connect it to the pc on excell transmits only the time and ch1, moreover the data of ch1 are received as zeros

**Comment by damyka** [comment]
Hi @mdadamo89, I am happy to help but I will need a little more information. 

The recommended and supported approach is to follow the build instructions here: https://aka.ms/fbfsbuildinstructions

Please make sure you have followed all of the directions. Once the Raspberry Pi, Grove Hat, and the sensors are assembled, then please follow the directions for Flashing the SD card in the Appendix (last section of the instructions). 

At this point you should be able to see data in Data Streamer. The project is designed to be used with a custom workbook here:  https://aka.ms/FBFSWorkbook. You can also use a blank workbook to test it, but there is functionality built into the custom Excel workbook. The instructions assume that the Excel workbook is the UI for the Raspberry Pi.

If you are still getting errors, please detail the exact steps that you took so that I can try and reproduce the issue and help you with troubleshooting. Please include if and how you are connecting to the Raspberry Pi.

**Comment by mdadamo89** [comment]
good evening! I performed all the steps he indicated to me, that is: I opened the file for assembling the Raspberry, then I  downloaded
 -farmbeats-image-builder 
-https://downloads.raspberrypi.org/imager/imager_latest.exe . Ho eseguito la procedura per l'installazione ho estratto la micro SD datl I performed the installation procedure and extracted the micro SD from the PC, then the micro SD was inserted into the Raspberry. I opened data streamer but it doesn't give me anything. the page is blank.

**Comment by mdadamo89** [comment]
good evening! I performed all the steps he indicated to me, that is: I opened the file for assembling the Raspberry, then I  downloaded
 -farmbeats-image-builder 
-https://downloads.raspberrypi.org/imager/imager_latest.exe . Ho eseguito la procedura per l'installazione ho estratto la micro SD datl I performed the installation procedure and extracted the micro SD from the PC, then the micro SD was inserted into the Raspberry. I opened data streamer but it doesn't give me anything. the page is blank.

**Comment by damyka** [comment]
HI @mdadamo89, I have received your updates. Please respond here with a comment for continuity. Thanks.

I understand that you were able to successfully assemble the Raspberry Pi and sensors, and that you flashed the SD card correctly, but Data Streamer page was blank. 

To check that the Raspberry Pi is connected to Data Streamer: 
- Be sure that Data Streamer can connect with the Raspberry Pi make sure that the Serial-TTL Cable wires are correctly connected to the Raspberry Pi. Verify with the diagrams in the instructions.
- Make sure that the device is visible in Data Streamer, and then connect to it. You can read more about how to use Data Streamer [here](https://support.microsoft.com/en-us/topic/navigating-the-ribbon-in-data-streamer-9c4caee5-5504-40e2-8015-8c9be5567476).
- Once connected, click on the Start Data button to begin streaming data.

If you are having more issues with Data Streamer, please open a ticket: [https://edusupport.microsoft.com/support?product_id=hacking_stem](https://edusupport.microsoft.com/support?product_id=hacking_stem)

I hope this helps.

**Comment by mdadamo89** [comment]
good morning! the problem was in the "data streamer" settings. Once I followed the guide she gave me I was able to solve the problem. Thanks so much for the supporto

**Comment by damyka** [comment]
@mdadamo89 that is excellent news!
